language: go
notifications:
  email:
    - jwangsadinata@gmail.com
os:
  - linux
  - osx
go:
  - 1.5
  - 1.6
  - 1.7
  - 1.8
  - 1.9
  - 1.10
  - tip
before_install:
  - go get github.com/mattn/goveralls
script:
  - go test -v -coverprofile=coverage.out
  - goveralls -service=travis-ci -coverprofile=coverage.out